### ISSUE TITLE
Demo scene EventSystem uses old UNITY input (but works with new UNITY input as well)

### ISSUE THREAD

**Issue by jpetays** [tomazsaraiva/unity-canvas-page-slider#2]
Demo scenes **EventSystem** _GameObject_ uses old UNITY input system but it is easy to replace with new UNITY input system when you click on **EventSystem** _GameObject_ and let UNITY change it - if your project is configured to use only new UNITY input system.

Maybe this could be stated on the README for those who might get upset when **InvalidOperationException** is thrown on the Console.

> **InvalidOperationException**: You are trying to read Input using the `UnityEngine.Input class`, but you have switched active Input handling to `Input System package` in Player Settings.

**Comment by tomazsaraiva** [comment]
@jpetays thanks for the heads-up. Instead of adding the warning in the README, should I update the project to use the new Input System? What do you think? Thanks

**Comment by jpetays** [comment]
IMHO it would be better to use old input system as the default as it is what UNITY offers for now.
Installing new input system requires some work and it should be no surprise or big obstacle to update event system after switching to the new one because it is so easy to do (if you know how to do it).

Luckily **ScrollRect** is input system agnostic so yo can keep your code simple and consistent.

**Comment by jpetays** [comment]
I think you can have the cake and eat it :-)

Change Project Settings -> Player -> Other Settings -> Active Input Handling -> Both.

Then duplicate your demo scenes and make the new set to use new `InputSystemUIInputModule`.
You just need to tell that there is demos for **both** old **and** new input system.

**Comment by tomazsaraiva** [comment]
I believe there's no need to duplicate the scenes. It's a project level setting that when's on "Both" it does not affect the current scene behaviour.

**Comment by jpetays** [comment]
> I believe there's no need to duplicate the scenes. It's a project level setting that when's on "Both" it does not affect the current scene behaviour.

**Yes, you are true**. But the settings is **not** managed by your scenes in your `.unitypackage` file and you have no way to enforce that somebody would use the "Both" setting.
I'm a strict guy so for me its all or nothing and "Both" setting is for those who are more easy-going and don't mind mixing different input system code bases together (and potentially making build output larger).

To prevent yourself having this discussion again I suggest that you just mention that demo scenes are using `StandaloneInputModule` Input Manage (Old) in Player settings.
I assume that those who are using Input System Package (New) know how to fix this issue as they must have done it at least few times already.

**Comment by tomazsaraiva** [comment]
@jpetays got it. You are right. Just added it to the documentation. Thank you for your contribution.
