### ISSUE TITLE
Feature Request: Scroll mode: One Page at a Time or Endless Scroller

### ISSUE THREAD

**Issue by jpetays** [tomazsaraiva/unity-canvas-page-slider#4]
Currently it seems that only **Endless Scroller** mode is implemented.
For some purposes it would be better or more intuitive to scroll only **one page at a time**.

Mobile photo viewers are good example.
In All Photos view scrolling is "endless" and reacts to swipe force but when viewing single photos scrolling is in "one picture at time" mode so you can not overshoot scrolling (and miss pictures) in any way.

**Comment by tomazsaraiva** [comment]
I'm not sure if I understand. Can you provide an example with your use case?

**Comment by jpetays** [comment]
I have to re-check this with my graphics designer as it was they that mentioned this to me.
I'm only using your supplied demo scenes which have three items to scroll so it is not possible to produce as it obviously needs more items to have this issue.

From the code it might be possible that is related to PageScroller OnEndDrag lines:
```
            // Determine if a page change should occur based on the current position and the switchPageBreakpoint.
            // If it's a forward drag and the current position is greater than the switchPageBreakpoint, 
            // it means the user has dragged enough to switch to the next page.
            // Similarly, for a backward drag, if the current position is less than the switchPageBreakpoint, 
            // a page change to the previous page is triggered.
            var page = _currentPage;
            if (isForwardDrag && currentPosition > switchPageBreakpoint)
            {
                page++;
            }
            else if (!isForwardDrag && currentPosition < switchPageBreakpoint)
            {
                page--;
            }
```
This code seems perfectly correct but it does not mean that behaves is it intended to work.  
I guess the `PageScroller` implementation intention is: one swipe moves one page at a time.

AFAIK mobile photo viewers work in two modes that work very differently in different viewing situations:
- free endless scrolling (no snapping to image), the viewport (screen) can be stopped in any position between start and end
- one picture at a time (snap to image), the viewport (screen) can be moved one image forwards/backwards at a time regardless swipe force

So the interesting part here is that you could have two scrolling modes that behave differently.
Obviously your plugin is intended only for the latter behavior as UNITY ScrollView provides to former out of the box.
_I'll talk with my friend if there is actually some problem that they don't like or behaves erratically..._

**Comment by jpetays** [comment]
This can be closed. PageScroller works A-OK.
It was my misunderstanding that scrolling could skip pages with enough swipe force etc.

**Comment by tomazsaraiva** [comment]
I’ll close this comment for now, but I’ll keep the feature we discussed in mind. Thanks!
