### ISSUE TITLE
PageSlider does not send initial page change notification

### ISSUE THREAD

**Issue by jpetays** [tomazsaraiva/unity-canvas-page-slider#9]
This feature might be by design or by mistake.
My use case is that I have header component that displays the current page "title".
If it does no receive page changed notification it can not set title text correctly (on start) because it does not know which page is displayed.
Normal page (swipe) navigation works correctly after start.

Call to  _scroller.SetPage() calls back PageScroller_PageChangeEnded which then triggers the page change notification.
If `_startPageIndex == 0` this call is not made and the notification is not sent. For me this is an error.

Original code:
```
        private IEnumerator Start()
        {
            _scroller.OnPageChangeStarted.AddListener(PageScroller_PageChangeStarted);
            _scroller.OnPageChangeEnded.AddListener(PageScroller_PageChangeEnded);

            yield return new WaitForEndOfFrame();

            if (_startPageIndex == 0) yield break;
            _scroller.SetPage(_startPageIndex, forceTeleport: true);
        }
```
Changed code:
```
        private IEnumerator Start()
        {
            _scroller.OnPageChangeStarted.AddListener(PageScroller_PageChangeStarted);
            _scroller.OnPageChangeEnded.AddListener(PageScroller_PageChangeEnded);

            yield return new WaitForEndOfFrame();

            if (_startPageIndex == 0)
            {
                OnPageChanged?.Invoke(_pages[0]);
                yield break;
            }
            _scroller.SetPage(_startPageIndex, forceTeleport: true);
        }
```

**Comment by tomazsaraiva** [comment]
@jpetays you are right. It was a mistake. Updated in develop. Thank you for your contribution.
